# Generated by Django 2.2.15 on 2020-08-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('documento', models.BigIntegerField()),
                ('fechanacimiento', models.DateField()),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.BigIntegerField()),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('lugarresidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Ciudad')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.TipoDocumento')),
            ],
        ),
    ]
